-- Apply with:
-- docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U app -d appdb < db/seeds/development.sql
INSERT INTO
    seller (name, website_url)
VALUES
    ('ALDI Nord', 'https://www.aldi-nord.de'),
    ('ALDI SÜD', 'https://www.aldi-sued.de'),
    ('Amazon.de', 'https://www.amazon.de'),
    ('dm-drogerie markt', 'https://www.dm.de'),
    ('EDEKA', 'https://www.edeka.de'),
    ('Kaufland', 'https://www.kaufland.de'),
    ('Lidl', 'https://www.lidl.de'),
    ('MediaMarkt', 'https://www.mediamarkt.de'),
    ('REWE', 'https://www.rewe.de'),
    ('ROSSMANN', 'https://www.rossmann.de') ON CONFLICT (lower(name)) DO NOTHING;

INSERT INTO
    category (name_de, name_en)
VALUES
    ('Getränke', 'beverages'),
    ('Reinigung', 'cleaning'),
    ('Bekleidung', 'clothing'),
    ('Kosmetik', 'cosmetics'),
    ('Elektronik', 'electronics'),
    ('Lebensmittel', 'food'),
    ('Haushalt', 'household'),
    ('Körperpflege', 'personal-care'),
    ('Tierbedarf', 'pet-care'),
    ('Nahrungsergänzung', 'supplements') ON CONFLICT (lower(name_de)) DO NOTHING;

INSERT INTO
    brand (name)
VALUES
    ('Acer'),
    ('Adidas'),
    ('Adobe'),
    ('Aesop'),
    ('Alnatura'),
    ('Apple'),
    ('Ariel'),
    ('Arla'),
    ('Asus'),
    ('Avène'),
    ('Balea'),
    ('alverde'),
    ('babylove'),
    ('Barilla'),
    ('Bauknecht'),
    ('Bayer'),
    ('Beats'),
    ('Beiersdorf'),
    ('Belkin'),
    ('Ben & Jerry''s'),
    ('Beste Wahl'),
    ('Bepanthen'),
    ('Bertolli'),
    ('Bio Company'),
    ('Bioderma'),
    ('Birkenstock'),
    ('Bosch'),
    ('Braun'),
    ('Bridgestone'),
    ('Brita'),
    ('Bruno Banani'),
    ('Bübchen'),
    ('Catrice'),
    ('Cien'),
    ('Coca-Cola'),
    ('Colgate'),
    ('Converse'),
    ('Dallmayr'),
    ('Denkmit'),
    ('domol'),
    ('EDEKA Bio'),
    ('enerBiO'),
    ('Dr. Oetker'),
    ('Ecover'),
    ('Ehrmann'),
    ('Elmex'),
    ('Fackelmann'),
    ('Fanta'),
    ('Fisher-Price'),
    ('Frosch'),
    ('Gut & Günstig'),
    ('Gut Bio'),
    ('Garmin'),
    ('Garnier'),
    ('Gilette'),
    ('Gorenje'),
    ('Haribo'),
    ('Head & Shoulders'),
    ('Hipp'),
    ('Hugo Boss'),
    ('Iglo'),
    ('Ikea'),
    ('Isana'),
    ('Ja!'),
    ('Jack Wolfskin'),
    ('Jacobs'),
    ('Kärcher'),
    ('K-Classic'),
    ('K-Beauty'),
    ('Kellogg''s'),
    ('Kérastase'),
    ('Kikkoman'),
    ('Kneipp'),
    ('Knorr'),
    ('Lenovo'),
    ('Levi''s'),
    ('LG'),
    ('L''Oréal'),
    ('Lindt'),
    ('Lacura'),
    ('Lupilu'),
    ('Logitech'),
    ('Lowa'),
    ('Maggi'),
    ('Mammut'),
    ('Manner'),
    ('Mars'),
    ('Miele'),
    ('Milka'),
    ('Milbona'),
    ('Milsani'),
    ('Monster Energy'),
    ('Müller'),
    ('Naduria'),
    ('Nescafé'),
    ('Nestlé'),
    ('Nike'),
    ('Nivea'),
    ('Nintendo'),
    ('Nivea Men'),
    ('Odol-med3'),
    ('Oral-B'),
    ('Oreo'),
    ('Pampers'),
    ('Parkside'),
    ('Patagonia'),
    ('Persil'),
    ('Philips'),
    ('Pilos'),
    ('PlayStation'),
    ('Puma'),
    ('Ritter Sport'),
    ('Samsung'),
    ('Sebamed'),
    ('Siemens'),
    ('Silvercrest'),
    ('Sony'),
    ('Speick'),
    ('Spotify'),
    ('Tchibo'),
    ('Tandil'),
    ('Tempo'),
    ('Tefal'),
    ('The North Face'),
    ('Toffifee'),
    ('Tupperware'),
    ('Vanish'),
    ('Varta'),
    ('Weleda'),
    ('W5'),
    ('Whiskas'),
    ('Wrigley''s'),
    ('Zalando'),
    ('Zewa') ON CONFLICT (lower(name)) DO NOTHING;

DO $$
BEGIN
   FOR counter IN 1..1000 LOOP
      INSERT INTO report (
          seller_id,
          brand_id,
          category_id,
          submitted_by_user_id,
          product_name,
          description,
          observed_at
      )
      VALUES (
          -999,
          -999,
          -999,
          -999,
          'p' || counter,
          'd' || counter,
          '2024-05-15'
      );
   END LOOP;
END;
$$;