-- Apply with:
-- docker compose exec -T postgres psql -U app -d appdb < backend/internal/db/seeds/development.sql
INSERT INTO
    sellers (name, website_url, country_code)
VALUES
    ('ALDI Nord', 'https://www.aldi-nord.de', 'DE'),
    ('ALDI SÜD', 'https://www.aldi-sued.de', 'DE'),
    ('Amazon.de', 'https://www.amazon.de', 'DE'),
    ('dm-drogerie markt', 'https://www.dm.de', 'DE'),
    ('EDEKA', 'https://www.edeka.de', 'DE'),
    ('Kaufland', 'https://www.kaufland.de', 'DE'),
    ('Lidl', 'https://www.lidl.de', 'DE'),
    ('MediaMarkt', 'https://www.mediamarkt.de', 'DE'),
    ('REWE', 'https://www.rewe.de', 'DE'),
    ('ROSSMANN', 'https://www.rossmann.de', 'DE') ON CONFLICT (lower(name)) DO NOTHING;

INSERT INTO
    categories (slug)
VALUES
    ('beverages'),
    ('cleaning'),
    ('clothing'),
    ('cosmetics'),
    ('electronics'),
    ('food'),
    ('household'),
    ('personal-care'),
    ('pet-care'),
    ('supplements') ON CONFLICT (lower(slug)) DO NOTHING;

INSERT INTO
    category_translations (category_id, locale, name)
SELECT
    category.id,
    translation.locale,
    translation.name
FROM
    (
        VALUES
            ('beverages', 'de', 'Getränke'),
            ('beverages', 'en', 'Beverages'),
            ('cleaning', 'de', 'Reinigung'),
            ('cleaning', 'en', 'Cleaning'),
            ('clothing', 'de', 'Bekleidung'),
            ('clothing', 'en', 'Clothing'),
            ('cosmetics', 'de', 'Kosmetik'),
            ('cosmetics', 'en', 'Cosmetics'),
            ('electronics', 'de', 'Elektronik'),
            ('electronics', 'en', 'Electronics'),
            ('food', 'de', 'Lebensmittel'),
            ('food', 'en', 'Food'),
            ('household', 'de', 'Haushalt'),
            ('household', 'en', 'Household'),
            ('personal-care', 'de', 'Körperpflege'),
            ('personal-care', 'en', 'Personal care'),
            ('pet-care', 'de', 'Tierbedarf'),
            ('pet-care', 'en', 'Pet care'),
            ('supplements', 'de', 'Nahrungsergänzung'),
            ('supplements', 'en', 'Supplements')
    ) AS translation (slug, locale, name)
    JOIN categories AS category ON category.slug = translation.slug ON CONFLICT (category_id, locale) DO
UPDATE
SET
    name = EXCLUDED.name;

INSERT INTO
    brands (name)
VALUES
    ('Acer'),
    ('Adidas'),
    ('Adobe'),
    ('Aesop'),
    ('Alnatura'),
    ('Apple'),
    ('Ariel'),
    ('Arla'),
    ('Asus'),
    ('Avène'),
    ('Balea'),
    ('alverde'),
    ('babylove'),
    ('Barilla'),
    ('Bauknecht'),
    ('Bayer'),
    ('Beats'),
    ('Beiersdorf'),
    ('Belkin'),
    ('Ben & Jerry''s'),
    ('Beste Wahl'),
    ('Bepanthen'),
    ('Bertolli'),
    ('Bio Company'),
    ('Bioderma'),
    ('Birkenstock'),
    ('Bosch'),
    ('Braun'),
    ('Bridgestone'),
    ('Brita'),
    ('Bruno Banani'),
    ('Bübchen'),
    ('Catrice'),
    ('Cien'),
    ('Coca-Cola'),
    ('Colgate'),
    ('Converse'),
    ('Dallmayr'),
    ('Denkmit'),
    ('domol'),
    ('EDEKA Bio'),
    ('enerBiO'),
    ('Dr. Oetker'),
    ('Ecover'),
    ('Ehrmann'),
    ('Elmex'),
    ('Fackelmann'),
    ('Fanta'),
    ('Fisher-Price'),
    ('Frosch'),
    ('Gut & Günstig'),
    ('Gut Bio'),
    ('Garmin'),
    ('Garnier'),
    ('Gilette'),
    ('Gorenje'),
    ('Haribo'),
    ('Head & Shoulders'),
    ('Hipp'),
    ('Hugo Boss'),
    ('Iglo'),
    ('Ikea'),
    ('Isana'),
    ('Ja!'),
    ('Jack Wolfskin'),
    ('Jacobs'),
    ('Kärcher'),
    ('K-Classic'),
    ('K-Beauty'),
    ('Kellogg''s'),
    ('Kérastase'),
    ('Kikkoman'),
    ('Kneipp'),
    ('Knorr'),
    ('Lenovo'),
    ('Levi''s'),
    ('LG'),
    ('L''Oréal'),
    ('Lindt'),
    ('Lacura'),
    ('Lupilu'),
    ('Logitech'),
    ('Lowa'),
    ('Maggi'),
    ('Mammut'),
    ('Manner'),
    ('Mars'),
    ('Miele'),
    ('Milka'),
    ('Milbona'),
    ('Milsani'),
    ('Monster Energy'),
    ('Müller'),
    ('Naduria'),
    ('Nescafé'),
    ('Nestlé'),
    ('Nike'),
    ('Nivea'),
    ('Nintendo'),
    ('Nivea Men'),
    ('Odol-med3'),
    ('Oral-B'),
    ('Oreo'),
    ('Pampers'),
    ('Parkside'),
    ('Patagonia'),
    ('Persil'),
    ('Philips'),
    ('Pilos'),
    ('PlayStation'),
    ('Puma'),
    ('Ritter Sport'),
    ('Samsung'),
    ('Sebamed'),
    ('Siemens'),
    ('Silvercrest'),
    ('Sony'),
    ('Speick'),
    ('Spotify'),
    ('Tchibo'),
    ('Tandil'),
    ('Tempo'),
    ('Tefal'),
    ('The North Face'),
    ('Toffifee'),
    ('Tupperware'),
    ('Vanish'),
    ('Varta'),
    ('Weleda'),
    ('W5'),
    ('Whiskas'),
    ('Wrigley''s'),
    ('Zalando'),
    ('Zewa') ON CONFLICT (lower(name)) DO NOTHING;

DO $$
BEGIN
   FOR counter IN 1..1000 LOOP
      INSERT INTO deterioration_reports (
          seller_id,
          brand_id,
          category_id,
          submitted_by_user_id,
          product_name,
          description,
          observed_at,
          status
      )
      VALUES (
          -999,
          -999,
          -999,
          1,
          'p' || counter,
          'd' || counter,
          '2024-05-15',
          'pending'
      );
   END LOOP;
END;
$$;